apiVersion: v1
kind: Service
metadata:
  name: threat-api-svc
  labels:
    app: threat-api
    tier: backend
spec:
  type: NodePort 
  selector:
    app: threat-api
    tier: backend
  ports:
  - port: 8000
    targetPort: 8000
    name: http
    protocol: TCP